//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceUtils.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceUtils.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;world_maxs&quot; &quot;4232 3712 1756&quot;
        ///&quot;world_mins&quot; &quot;-5880 -4264 -20&quot;
        ///&quot;skyname&quot; &quot;sky_cs15_daylight01_hdr&quot;
        ///&quot;maxpropscreenwidth&quot; &quot;-1&quot;
        ///&quot;detailvbsp&quot; &quot;detail.vbsp&quot;
        ///&quot;detailmaterial&quot; &quot;detail/detailsprites&quot;
        ///&quot;classname&quot; &quot;worldspawn&quot;
        ///&quot;mapversion&quot; &quot;17816&quot;
        ///&quot;hammerid&quot; &quot;1&quot;
        ///}
        ///{
        ///&quot;model&quot; &quot;*1&quot;
        ///&quot;vrad_brush_cast_shadows&quot; &quot;0&quot;
        ///&quot;StartDisabled&quot; &quot;0&quot;
        ///&quot;spawnflags&quot; &quot;2&quot;
        ///&quot;Solidity&quot; &quot;2&quot;
        ///&quot;solidbsp&quot; &quot;0&quot;
        ///&quot;shadowdepthnocache&quot; &quot;0&quot;
        ///&quot;rendermode&quot; &quot;0&quot;
        ///&quot;renderfx&quot; &quot;0&quot;
        ///&quot;rendercolor&quot; &quot;255 255 255&quot;
        ///&quot;renderamt&quot; &quot;255&quot;
        ///&quot;origin&quot; &quot;-3274 -38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string entities {
            get {
                return ResourceManager.GetString("entities", resourceCulture);
            }
        }
    }
}
